name: Parallel Jobs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: |
          ls -ltr
          touch test1.txt
  build:
  #  needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: |
          ls -ltr
          touch test2.txt
  test:
  #  needs: build
    runs-on: ubuntu-latest
    steps:
      - run: |
          ls -ltr
          touch test3.txt
          ls -ltr
      - uses: iRoachie/slack-github-actions@v2.3.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
        if: ${{ always() }}
